### ISSUE TITLE
HTTPS Fail

### ISSUE THREAD

**Issue by benklocek** [moderntribe/image-widget#10]
Seems that the plugin does not respect secure URLS. Perhaps a relative URL, or protocol-less?

**Comment by peterchester** [comment]
When you say does not "respect secure URLS" I'm not sure what you mean. Can you be more specific?

**Comment by benklocek** [comment]
Sorry for the lack of detail. I was hoping to be able to send you a pull request, but I'm not sure what's going on.

I have some pages (specifically a checkout page) that are "https", but most are simply "http". It seems that the plugin stores the image URL, rather than getting it on each page load, so is_ssl() is not checked, leaving me with insecure elements on the pages that are https.

I'm guessing that perhaps I just need to make the whole site https.

**Comment by peterchester** [comment]
Try filtering “image_widget_image_url”.

I see what you mean and why this is probably happening. But you should be able to build a simple workaround with that.

> On Mar 17, 2015, at 10:52 AM, Ben Klocek <notifications@github.com> wrote:
> 
> Sorry for the lack of detail. I was hoping to be able to send you a pull request, but I'm not sure what's going on.
> 
> I have some pages (specifically a checkout page) that are "https", but most are simply "http". It seems that the plugin stores the image URL, rather than getting it on each page load, so is_ssl() is not checked, leaving me with insecure elements on the pages that are https.
> 
> I'm guessing that perhaps I just need to make the whole site https.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/moderntribe/image-widget/issues/10#issuecomment-82496782>.
> 

---
Chaim Peter Chester
Modern Tribe, Inc.
(831) 345 6341
@peterchester

**Comment by benklocek** [comment]
Perfect. Will do.
