### ISSUE TITLE
New install, says thanks for *upgrading*

### ISSUE THREAD

**Issue by pmgarman** [moderntribe/image-widget#22]
Just installed the plugin, yet the notice on the top of the screen was as if I'd upgraded it. Just feels a bit out of place and that the wording could be improved upon for new installs.

> Thanks for upgrading the Image Widget! If you like this plugin, please consider rating it and maybe even check out our premium plugins including our Events Calendar Pro!

**Comment by ggwicz** [comment]
Great point, @pmgarman. We've fixed this in the most recent version of Image Widget—it will now saw, "Thanks for _using_ the Image Widget", instead of "Thanks for upgrading the Image Widget".

Cheers,
George
